### ISSUE TITLE
Using getVercelOidcToken in edge function doesn't work

### ISSUE THREAD

**Issue by cbovis** [zeit/now#12071]
We're making use of `getVercelOidcToken` in our NextJS apps for talking to internal APIs. Today I tried using it within a NextJS route handler on the edge runtime and was left scratching my head with an error: `The 'x-vercel-oidc-token' header is missing from the request. Do you have the OIDC option enabled in the Vercel project settings?`.

The call works in development but that's because I have `VERCEL_OIDC_TOKEN` pulled down to my local environment. Only when deployed and executed does the call fail. Initially I figured it was a configuration issue since this is a new app and the first use of OIDC token generation in the app however switching to the NodeJS runtime instead of the Edge runtime resolved the issue.

So by using the NodeJS runtime I technically have a workaround but for performance reasons I would prefer to use the edge runtime if possible. This will be the only limiting factor as all other code in use is edge runtime compatible.

Looking through the package code I see that the header is being pulled from a global context: https://github.com/vercel/vercel/blob/main/packages/functions/src/oidc/get-vercel-oidc-token.ts#L27. It seems like this global context potentially isn't established in the Edge runtime, or at least isn't established with the required header.

Unsure of whether this is a bug or expected. If it's expected then it would be useful to have a call out in the OIDC docs stating that the function isn't compatible with the edge runtime since my expectation was that it would just work.

**Comment by trek** [comment]
Hey @cbovis,

Thanks for reaching out! We use this Issue tracker for bugs in the Vercel CLI and related open source libraries. For general platform help and feedback please open a new discussion at https://vercel.community. 

I've let the appropriate team know to be on the lookout for your post.

**Comment by smaeda-ks** [comment]
@cbovis, I saw an internal escalation from @trek and identified the issue. Will let you know once it's fixed. Thanks!

**Comment by cbovis** [comment]
Perfect, thanks @smaeda-ks !

**Comment by smaeda-ks** [comment]
@cbovis I've turned on a flag on your pro team that should fix the issue. Could you redeploy your app and test it again?

**Comment by cbovis** [comment]
Thanks @smaeda-ks it's working well with edge runtime now!

**Comment by Noahnrg** [comment]
Hello, I am a developer on the same project as @cbovis and wanted to note that today the same issue came back, with the fix being switching to the NodeJS runtime instead of the Edge runtime again.

Was there any regression that happened recently by chance? or is there anything i can do in vercel to update that flag you mentioned @smaeda-ks ?
