### ISSUE TITLE
x-middleware-rewrite discards URL search params with no value

### ISSUE THREAD

**Issue by teemingc** [zeit/now#12902]
When using the [`@vercel/edge` rewrite helper](https://vercel.com/docs/functions/edge-middleware/middleware-api#rewrites) or simply adding the `x-middleware-rewrite` header, URL search params with an empty string value are discarded. This impacts SvelteKit form actions which uses search params such as `?/login` to differentiate between different POST actions for a given route.

To reproduce this, visit https://vercel-rewrite-drab.vercel.app/?example and observe that the query parameter is missing from the text response because it has no value. In contrast, visit https://vercel-rewrite-drab.vercel.app/?example=true and observe that the query parameter is reflected in the text response because the query parameter has a value.

Repository: https://github.com/eltigerchino/vercel-rewrite

This was also reported in https://github.com/vercel/next.js/discussions/51023

EDIT: replaced the repro with a more minimal example

This affects SvelteKit's form actions with use query parameters without values such as `?/login`

**Comment by trek** [comment]
This was related to an ongoing issue that should be resolved now. Please let us know if it persists.

**Comment by teemingc** [comment]
Hi @trek . It seems that the issue still persists. Navigating to https://vercel-rewrite-drab.vercel.app/?example reveals that the URL search param is discarded

**Comment by teemingc** [comment]
Interestingly, it only discards it if there's only one instance of the key. If there are multiple of the same key e.g., `?example&example`, the search param isn't discarded

**Comment by teemingc** [comment]
Closing this in favour of the issue opened on the Vercel platform https://community.vercel.com/t/sveltekit-issues-on-the-vercel-platform/18042
