### ISSUE TITLE
@vercel/functions `attachDatabasePool` mysterious "Pool release event triggered outside of request scope" log

### ISSUE THREAD

**Issue by AryanJ-NYC** [zeit/now#13975]
As described in https://github.com/prisma/prisma/discussions/28061, the new `attachDatabasePool` function in `@vercel/functions` continuously logs "Pool release event triggered outside of request scope." Is this anything to be concerned about?

**Comment by justinvitale** [comment]
Hey @AryanJ-NYC , these log lines are debug messages and can safely be ignored. We've released a fix in the latest version of `@vercel/functions` which prevents these from being surfaced by default—please update your `@vercel/functions` dependency and you should no longer see this.

**Comment by mr-robek** [comment]
hey @justinvitale , I am using the newest @vercel/functions package (3.3.4) but I still see this log in my log files. should I be worried about it?
