### ISSUE TITLE
Serverless Function crashing due to `Cannot find module '/var/task/backend/node_modules/axios/dist/node/axios.cjs'`

### ISSUE THREAD

**Issue by cmgchess** [zeit/now#9769]
### Discussed in https://github.com/vercel/vercel/discussions/9637

<div type='discussions-op-text'>

<sup>Originally posted by **cmgchess** March  9, 2023</sup>
Hello 👋
I have a serverless function and it works locally using `vercel dev` but fails when I deploy it.   
[Here](https://github.com/cmgchess/fide-ui/tree/master/backend) is the related repo.
I'm getting the error

```
Cannot find module '/var/task/backend/node_modules/axios/dist/node/axios.cjs'
Did you forget to add it to "dependencies" in `package.json`?
RequestId: f00c415d-275c-4c1e-b6a0-e9546687763e Error: Runtime exited with error: exit status 1
Runtime.ExitError
```

I have the following dependencies including `axios`
```json
  "devDependencies": {
    "@vercel/node": "^2.9.12"
  },
  "dependencies": {
    "axios": "^1.3.3",
    "cheerio": "^1.0.0-rc.12"
  }
```

I use Node 18 on Vercel. I'm not sure what's causing this since I can find the `axios.cjs` file when I check my `node_modules` folder
Also created a reproducible demo
https://github.com/cmgchess/vercel-serverless-axios-issue

Help much appreciated 🙏

![image](https://user-images.githubusercontent.com/61736812/224010460-ecb82788-853a-4e51-81a4-39d72679e538.png)
![image](https://user-images.githubusercontent.com/61736812/224009780-dee187fc-dd50-4324-ac2a-fc958a2edaa6.png)
![image](https://user-images.githubusercontent.com/61736812/224010271-8a1de724-6117-433b-ace5-6b11525b6c18.png)
</div>

**Comment by cb1kenobi** [comment]
This issue was resolved in the discussion: https://github.com/vercel/vercel/discussions/9637#discussioncomment-5258842.

**Comment by cmgchess** [comment]
> This issue was resolved in the discussion: [#9637 (comment)](https://github.com/vercel/vercel/discussions/9637#discussioncomment-5258842).

Unfortunately, it doesn't fully resolve since now I have to manually change the way I import when I test locally and when I want to deploy. I only found out later

**Comment by cb1kenobi** [comment]
Reopening to further investigate :)

**Comment by cb1kenobi** [comment]
I'm able to reproduce. Thank you for the test case. I've asked the team to see what they make of the issue. Stay tuned.

**Comment by cb1kenobi** [comment]
OK, I've done some investigation. `axios@1.3.3` is an ESM module which requires you to add `"type": "module"` to the `package.json`. That should fix deploying.

`vc dev` support for ESM is a little spotty. I have a PR https://github.com/vercel/vercel/pull/9692 that will address all known issues with using ESM dependencies. I'm hoping to land that PR "soon".

**Comment by jakeleventhal** [comment]
https://github.com/vercel/vercel/issues/8794 any chance this is related

**Comment by Dunky45** [comment]
> OK, I've done some investigation. `axios@1.3.3` is an ESM module which requires you to add `"type": "module"` to the `package.json`. That should fix deploying.
> 
> `vc dev` support for ESM is a little spotty. I have a PR #9692 that will address all known issues with using ESM dependencies. I'm hoping to land that PR "soon".

Hello, I'm sorry but I don't understand how this is a solution. This would require me to change imports throughout the whole app, wouldn't it? 

Btw. I still have this error on my Node.js API


`Cannot find module '/var/task/node_modules/axios/dist/node/axios.cjs'
Did you forget to add it to "dependencies" in `package.json`?
RequestId: ab697e49-3105-49cf-a678-11d1c20b30ef Error: Runtime exited with error: exit status 1
Runtime.ExitError`

**Comment by cb1kenobi** [comment]
@Dunky45 Hi! What version of `axios` are you using? I'd like to try and reproduce.

**Comment by Alafia-Ojo** [comment]
please i am still having this issue

**Comment by omerhochman** [comment]
Happens to me when I've added [@novu/node](https://www.npmjs.com/package/novu?activeTab=code) package to my application and deployed on vercel.

Adding axios to my app package.json didn't solve the issue

**Comment by irfanzainudin** [comment]
I'm having a similar issue with my Serverless Function crashing after I transferred my projects from the Hobby Plan to the Pro plan. Not sure if it's related, but here's my logs.

```
Cannot find module './common'
Require stack:
- /var/task/node_modules/debug/src/node.js
- /var/task/node_modules/debug/src/index.js
- /var/task/node_modules/knex/lib/execution/transaction.js
- /var/task/node_modules/knex/lib/client.js
- /var/task/node_modules/knex/lib/knex-builder/Knex.js
- /var/task/node_modules/knex/lib/index.js
- /var/task/node_modules/knex/knex.js
- /var/task/api/db.js
- /var/task/api/cariGunaKata.js
Did you forget to add it to "dependencies" in `package.json`?
INIT_REPORT Init Duration: 355.71 ms	Phase: init	Status: error	Error Type: Runtime.ExitError
Cannot find module './common'
Require stack:
- /var/task/node_modules/debug/src/node.js
- /var/task/node_modules/debug/src/index.js
- /var/task/node_modules/knex/lib/execution/transaction.js
- /var/task/node_modules/knex/lib/client.js
- /var/task/node_modules/knex/lib/knex-builder/Knex.js
- /var/task/node_modules/knex/lib/index.js
- /var/task/node_modules/knex/knex.js
- /var/task/api/db.js
- /var/task/api/cariGunaKata.js
Did you forget to add it to "dependencies" in `package.json`?
INIT_REPORT Init Duration: 448.64 ms	Phase: invoke	Status: error	Error Type: Runtime.ExitError
Error: Runtime exited with error: exit status 1
Runtime.ExitError
```

I tried a number of things including fixing my [letter-casing inconsistencies](https://vercel.com/guides/how-do-i-resolve-a-module-not-found-error) but nothing seems to fix it.

Please advise.

**Comment by jpgcodecr** [comment]
Seeing the same issue here. Any workarounds?

**Comment by aryangulati2k3** [comment]
I still haven't found a workaround

**Comment by kittymeow21** [comment]
changing from `axios` to `axios/dist/node/axios.cjs` helped me
`const axios = require('axios/dist/node/axios.cjs');`

axios version ^1.7.7

**Comment by rafaehlers** [comment]
FIY this solution worked for me: https://github.com/vercel/vercel/discussions/9637#discussioncomment-5258842

**Comment by tawfiqkhalilieh** [comment]
I don’t think this bug is fully reproducible.

I’ve been using Axios for years, in multiple apps I deployed myself and at my previous company, where every single frontend HTTP request went through axios, and I never encountered this problem.

Earlier today, I was helping a friend troubleshoot the same bug, and when I searched online, I came across this issue.

**Comment by ngudbhav** [comment]
I am facing the issue with mailgun.js@12.4.0.

```
Cannot find module '/var/task/node_modules/mailgun.js/CJS/mailgun.node.cjs'
Did you forget to add it to "dependencies" in `package.json`?
Node.js process exited with exit status: 1. The logs above can help with debugging the issue.
```

**Comment by Type-32** [comment]
Not sure whether this was related or not, but I think I might have a similar issue with using Tiptap on a nuxt environment deployed on vercel:

```log
Server 500

Cannot find module 'lib0/logging' from '/var/task/node_modules/yjs/dist/yjs.mjs'
```

I have `lib0` and `yjs` both installed as a dependency in the `package.json` and also have `"type": "module"` configured.

**Comment by HipyCas** [comment]
I've got a similar issue on my Nuxt v4 deployment, without making any change to the import that may have caused it. To be specific, the error is:

```
 Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/var/task/node_modules/unhead/dist/server.mjs' imported from /var/task/chunks/routes/renderer.mjs
````
